CANFLUX/Biomet.net

.gitignore, matlab/NEW_MET/trace_export.asv
%   - Automated Clean folder creation for the sites that don't have them.
%     If missing, it will create 'Clean\SecondStage', 'Flux\Clean',...
%     and such folders.
=> Edited trace_export.m  % Jan 25, 2023 (Zoran)

matlab/Micromet/BB_webupdate.m
Removed incorrect input paths (the "varStruct(*).type" field) of DO and SWin variables in BB_webupdate.m
=> remove incorrect input paths of DO and SWIN in BB_webupdate.m

matlab/Micromet/BB_webupdate.asv
Edits in DSM&RBM sections
(1) added net radiation 
(2) modified RBM headers from 3.5m to 6m
(3) deleted redundant conversions of ch4_flux
=> Edit BB_webupdate

matlab/Micromet/BB_webupdate.asv, matlab/Micromet/BB_webupdate.m
change input path from 2ndStage folders to 1stStage folders
=> Edited BB_webupdate.m

R/database_functions/ThirdStage_REddyProc.R
Updated the third stage to gap-fill and partition Ameriflux/FLUXNET input file
=> Stage three fluxnet

matlab/BIOMET/fr_automated_cleaning.m
Added BBS to micrometSites. 
Also split the try catch at the end:
The "DerivedVariablesForGapFilling" is a matlab function and should be handled separately from the python code.  If DerivedVariablesForGapFilling fails, the program will crash (without try/catch) and the python commands won't run (if nested within they try/catch).  The DerivedVariablesForGapFilling is a stopgap measure until we sort out a standardized procedure for gap-filling met data.  It dumps full traces (all years) of some standard met variables (TA, RH, etc.) from Clean/SecondStage and also calculates rolling averages on daily, monthly, and seasonal scales.  These can then be used to train multivariate regression models to gap-fill traces like soil temperature, VWC, etc. which need to be "complete" if they're to be …
=> Js updates

.gitignore, Python/ini_files/BiometPy.ini, R/database_functions/RandomForestModel.R, R/database_functions/ThirdStage.R
Added two new functions for third stage procedures:
**ThirdStage.R** is a parsed down version of the original that uses a YAML format config file (see pull in calculation procedures) to run REddyProc and Random forest gap filling.  I aimed to prioritized readability and brevity, so have separated code blocks into functions.  I also dropped some routines that were in the original (e.g., renaming REddyProc outputs), which could be added back if needed.
**RandomForest.R** is a streamlined rough draft of the RF model procedures.  It still needs some work to produce what I would consider a useful outputs (partly dependent on gap filling inputs first, which is an "upstream" task we've yet to complete).
=> Third stage updates

R/database_functions/RandomForestModelTest.R, R/database_functions/ThirdStage.R
=> Sk third stage updates

.gitignore, R/database_functions/RandomForestModel.R, R/database_functions/ThirdStage.R
1. Updated functionality of RF model, including printing validation statistics by default and saving plots to log folder.
2. Changed name of global configuration file from _config.yml to global_config.yml (see Calculation procedures)
3. Fixed bugs write_traces that was producing incorrectly labelled REddyProc outputs.
=> Rf updates

Python/config_files/config.yml, Python/config_files/csv_requests_template.yml, Python/csvFromBinary.py
Expanded capabilities to aggregate data and integrate requests with EddyPro API
=> Python dbase read

matlab/MET/absHumidityMet.m, matlab/MET/dewpointMet.m, matlab/MET/mixingRatioMet.m, matlab/MET/vapPressMet.m
New functions to calculate moisture variables from met data (ref. Stull):
absHumidityMet.m       
mixingRatioMet.m
dewpointMet.m
vapPressMet.m
=> Moisture functions using met data

R/database_functions/RandomForestModel.R, R/database_functions/ThirdStage.R, R/database_functions/db_root.R
Changes made with this pull request:
1. All existing site-years are now read into ThirdStage by default.  **However** ThirdStage will only write outputs to the database for years within the range startyear:endyear (if only startyear is provided, endyear=startyear) as per @znesic request
2. I fixed the database reading routine to be a bit more robust, by skipping empty traces instead of crashing.  Instead of altering the existing read_database.R function, I added a simplified version of the routine directly to ThirdStage.R so that it doesn't alter the expected behaviour of anyone using ReadDatabase.R for other purposes.
3. REddyProc will be given input data spanning Dec 1st (startyear - 1) to Feb 28/9 (endyear+1) wherever possible to maintain consistency with REddyProc season definitions. …
=> Thrid stage adjustments

matlab/Micromet/run_std_dev.m
With default argument (i.e. verbose=0), a conditional statement was preventing outliers being removed from the data passed back to the function caller.
=> Fixed bug in run_std_dev.m and added optional output arguments

matlab/New_eddy/fr_read_generic_data_file.m
function fr_read_generic_data_file()
Added more trace renaming rules. 
Current status:
% Characters to replace with "_"
replaceWithUnderscore = {'[','(','-','.','/',' ','°',''''};
% Characters to replace with ""
replaceWithEmpty = {']',')',':'};
% New way of renaming
% first run complex renaming:
renFieldsNew  = replace(fieldsIn,'u*','us');
renFieldsNew  = replace(renFieldsNew,'(z-d)/L','zdL');
renFieldsNew  = replace(renFieldsNew,'T*','ts');
renFieldsNew  = replace(renFieldsNew,'%','p');
renFieldsNew  = replace(renFieldsNew,replaceWithUnderscore,'_');
renFieldsNew  = replace(renFieldsNew,replaceWithEmpty,'');
renFieldsNew  = replace(renFieldsNew,'³','3');
renFieldsNew  = replace(renFieldsNew,'²','2');
renFieldsNew  = replace(renFieldsNew,'?','Q');
=> Zn new feature

matlab/BIOMET/db_ECCC_climate_station.m, matlab/BIOMET/run_ECCC_climate_station_update.m
Now using the new db_struct2database instead of db_save_struct function to convert the outStruct to database.
=> Updated ECCC processing 

matlab/TRACEANALYSIS_FIRSTSTAGE/read_ini_file.m
=> Bug fix: using globalVars.traceName.Evaluate did not work properly.

R/database_functions/ThirdStage.R, matlab/BIOMET/db_NCEI_climate_station.m
- Changed behaviour of how suffixes are appended so that _PI is only added after wind direction and precipitation filters are applied. With the new update, wind sector and precipitation filters are applied to the original flux imported from the second stage.
- Bug fix for db_NCEI_climate_station so that time offset is applied in hours instead of days.
- Added information to file header in db_NCEI_climate_station on where to find climate station ID numbers.
=> Update to ThirdStage suffixes

R/database_functions/ThirdStage.R
- The previous version of ThirdStage.R expected specific variable names: (1) SW_1_1_1; (2) WD_1_1_1; (3) P_1_1_1. The code has been updated to still work with these variable names by default. However, alternate variable names can now be specified in the site-speficic yml file under Processing:ThirdStage:REddyProc:vars_in
- For the three variables above, the default behaviour would be analogous to having: (1) Rg: SW_1_1_1; (2) WD: WD_1_1_1; and (3) P: P_1_1_1 under vars_in
=> Update ThirdStage.R to allow optional user input

R/database_functions/ThirdStage.R, matlab/Micromet/basic_error_check_yml_site_config.m, matlab/Micromet/runThirdStageCleaningREddyProc.m
- Created new function basic_error_check_yml_site_config.m to look for errors in site_config.yml, reports issues to Matlab command window, returns a flag for use by calling function.
- Modified runThirdStageCleaningREddyProc.m to skip call to ThirdStage.R if an error was detected in the site_config.yml
- Modified ThirdStage.R to include additional error checking: (1) Standard_Cleaning -- Checks if user has set precipCutOff to NULL; (2) Storage_Correction -- checks for empty storage correction terms, reports error, skips all storage terms if any are missing; (3) Papale_Spike_Removal -- checks SW variable name and that it contains data, checks for empty flux variable, reports error and allows script to continue; (4) REddyProc -- placed call to REddyPro inside tryCatch() with temporary error …
=> New error checking for Third Stage

matlab/Micromet/basic_error_check_yml_site_config.m
- Modified basic_error_check_yml...() for backwards compatibility. Defaults to checking the global_config.yml if the original site-spefic _config.yml format is detected.
=> _config.yml backwards compatibility update

matlab/BIOMET/read_R_log.m
- new function 'read_R_log()' called by fr_automated_cleaning() to read critical messages from ThirdStage to be displayed in Matlab command window.
=> New file for reading R log

matlab/TRACEANALYSIS_TOOLS/fr_compare_database_traces.m
To better distinguish new data and NaNs
=> Edited plot marker colour in fr_compare_database_traces

matlab/BIOMET/fr_automated_cleaning.m, matlab/New_eddy/fr_read_Ameriflux_file.m, matlab/TRACEANALYSIS_TOOLS/createAmerifluxThirdStageIni.m, matlab/TRACEANALYSIS_TOOLS/ta_plot_parents.m
Added function: fr_read_Ameriflux_file.
Added function: createAmerifluxThirdStageIni
Bug fixes:
- removed some '\' from paths to improve compatibility between macOS and Windows
Improvements:
- changed line thickness in ta_plot_parents
=> Added new functions and fixed a couple of bugs

Python/methaneGapfillML.py, matlab/BIOMET/fr_automated_cleaning.m
With these changes, the ML pipeline will now use the YAML files in `Biomet.net/Python/config_files` as a _default_, and update based on the existence of a YAML file in the `Calculation_Procedures/TraceAnalysis_ini`.
A few other minor changes to the adapter.
=> ML config changes

matlab/BIOMET/db_NCEI_climate_station.m
- some NCEI sites are on 30 min interval instead of hourly, so function was updated to check time vector to determine the interval automatically
- NCEI site IDs can start with a zero, so ID needs to be a string instead of a number. Code was updated to accommodate a string input for site ID.
=> Update to db_NCEI_climate_station

matlab/BIOMET/db_NCEI_climate_station.m
- previous version of code assumed that NCEI data was either hourly or half-hourly
- updated code to handle sites with inconsistent reporting intervals
- code now extracts (interpolated) hourly data, ignoring periods with multi-hour gaps
=> Update to db_NCEI_climate_station.m

Python/methaneGapfillML.py
One last feature for the ML gapfilling pipeline. As per Haley's request, you can now (optionally) specify per-site configuration files. The `TraceAnalysis.ini` directory may now look like:
```
TraceAnalysis_ini
├── CH4_ML_Gapfill.yml      <-- Will override default config
├── ECCC_FirstStage_include.ini
├── ...
├── README.md
├── Site1
│   ├── CH4_ML_Gapfill.yml     <-- Will override default config and parent config
│   ├── ...
│   └── SMC_SecondStage.ini
├── Site2
│   ├── CH4_ML_Gapfill.yml     <-- Will override default config and parent config
│   ├── ...
│   └── SMC_SecondStage.ini
```
=> Add site-specific ML gapfill config support
